#version: "3.9"

networks:
  openclaw-net:
    driver: bridge

services:

  openclaw:
    image: ghcr.io/openclaw/openclaw:latest
    container_name: openclaw
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: "9dc6cd9b4407522d0e1984b4864ddf3dbf8b97a50072e02482e2533fc6fb2bfe"
      OPENCLAW_GATEWAY_CONTROLUI_ALLOWEDORIGINS: "https://10.88.1.78:8443"
      OPENCLAW_GATEWAY_CONTROLUI_DANGEROUSLYALLOWHOSTHEADERORIGINFALLBACK: "true"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./config:/home/node/.openclaw
      - ./workspace:/home/node/.openclaw/workspace
    command:
      [
        "node",
        "openclaw.mjs",
        "gateway",
        "--bind",
        "lan",
        "--allow-unconfigured"
      ]
    depends_on:
      - fila-api
    networks:
      - openclaw-net
    restart: unless-stopped


  nginx:
    image: nginx:alpine
    container_name: openclaw-nginx
    ports:
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl
    depends_on:
      - openclaw
    networks:
      - openclaw-net
    restart: unless-stopped


  postgres:
    image: postgres:16
    container_name: fila-db
    environment:
      POSTGRES_DB: hospital
      POSTGRES_USER: hospital
      POSTGRES_PASSWORD: hospital123
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - openclaw-net
    restart: unless-stopped


  fila-api:
    build: ./api
    container_name: fila-api
    environment:
      DB_HOST: postgres
      DB_NAME: hospital
      DB_USER: hospital
      DB_PASSWORD: hospital123
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    networks:
      - openclaw-net
    restart: unless-stopped


volumes:
  postgres-data: